QPPSE-1512: Manual update of measure-data
CMSgov/qpp-conversion-tool pull request #1402
Opened 2023-12-12 21:01 UTC by saquino0827

### Information
- Temporarily update measures data manually and comment out measure-data update script until QPPSE-1512 is fixed.

### Checklist 
- [ ] All JUnit tests pass (`mvn clean verify`).
- [ ] New unit tests written to cover new functionality.
- [ ] Added and updated JavaDocs for non-test classes and methods.
- [ ] No local design debt. Do you feel that something is "ugly" after your changes?
- [ ] Updated documentation (`README.md`, etc.) depending if the changes require it.

2023-12-12 21:13 UTC, cabedi-icf approved these changes

2023-12-12 21:24 UTC, Jpec07 submitted a review, later dismissed

2023-12-12 22:49 UTC, sivaksb requested changes
CMS347v6 seems to be missing as well.  Is it on purpose?

2023-12-13 15:58 UTC, saquino0827 commented
> CMS347v6 seems to be missing as well. Is it on purpose?

Nice catch, this was missed and I've added it manually. This will need to be added to QPPSE-1513.

2023-12-13 16:17 UTC, sivaksb approved these changes

2023-12-13 18:03 UTC, sivaksb approved these changes

2023-12-13 18:07 UTC, merged