[DEVOPS][QPPSE-1710] Grant S3 CPC Bucket permissions to Codebuild service role
CMSgov/qpp-conversion-tool pull request #1412
Opened 2024-02-01 19:29 UTC by rajkpammi

### Information
- Fixes #_
- _QPPSE-1710_ 

### Changes proposed in this PR:
* Tf changes to allow access on s3 cpc buckets for codebuild iam service role*
* Added new env variable pertaining to s3 CPC buckets to match the naming convention on the buckets*

### Checklist 
- [ ] All JUnit tests pass (`mvn clean verify`).
- [ ] New unit tests written to cover new functionality.
- [ ] Added and updated JavaDocs for non-test classes and methods.
- [ ] No local design debt. Do you feel that something is "ugly" after your changes?
- [ ] Updated documentation (`README.md`, etc.) depending if the changes require it.

2024-02-06 15:58 UTC, Jpec07 approved these changes

2024-02-06 22:43 UTC, sivaksb requested changes

2024-02-26 19:07 UTC, Brekmsmed requested changes
[QRDA_1_SCHEXNAIDER_ KERRY_20230101_20231231_CMS_68.ZIP](https://github.com/CMSgov/qpp-conversion-tool/files/14409687/QRDA_1_SCHEXNAIDER_.KERRY_20230101_20231231_CMS_68.ZIP)

2024-08-06 23:18 UTC, Alfred182 approved these changes

2024-09-05 13:16 UTC, closed without merging

2024-12-23 16:25 UTC, Alfred182 reviewed
Viewed